/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Overlays {
	/**
	 * This interface was referenced by `Overlays`'s JSON-Schema definition
	 * via the `patternProperty` "^.*$".
	 */
	[k: string]: boolean;
}
